# -*- coding: utf-8 -*-
"""Sprints.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JaEZxew74-N77mB0t_sQc6fLq-K9J0rv
"""

!nvidia-smi

import os
HOME=os.getcwd()
print(HOME)

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="rkJEYbBxdZ7x6j4ZFHVF")
project = rf.workspace("paul-1b02h").project("mark-a6cfg")
dataset = project.version(2).download("yolov8")

!pip install ultralytics
from ultralytics import YOLO

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=train model=yolov8x.pt data={dataset.location}/data.yaml epochs=500 imgsz=640

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=val model=/content/runs/detect/train6/weights/best.pt data={dataset.location}/data.yaml

!yolo task=detect mode=predict model=/content/runs/detect/train6/weights/best.pt source={dataset.location}/test/images

project.version(dataset.version).deploy(model_type="yolov8",model_path="/content/runs/detect/train6")

from IPython import display
from IPython.display import display, Image

Image(filename='/content/runs/detect/train6/confusion_matrix.png',width=600)

Image(filename='/content/runs/detect/train6/results.png',width=600)

Image(filename='/content/runs/detect/val2/val_batch0_pred.jpg',width=600)

Image(filename='/content/runs/detect/predict3/test-paper-1_16_jpg.rf.ec01e2f73b7f4358a1083d7495bfd083.jpg',width=600)